**numpy**

In [31]:
import numpy as np # numpy kütüphanesini np takma adı ile projeye dahil olur

In [6]:
# yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [5]:
dizi=np.full((4,3),5)#çoklu satır ve sütun veriyor 5 değerini veriyor
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [15]:
dizi

array([1.  , 2.  , 3.14])

In [16]:
dizi=np.array([1,2,3])

In [14]:
dizi=np.array([1,2,3.14])

In [ ]:
dizi.type #dizinin değişken türünü verir. numpy dizilerinde elemanların hepsi aynı türdendir 

In [ ]:
dtype('float64')

In [28]:
dizi=np.array([1,2,3.14], dtype=int)

**numpy farklı boyut dizileri**

In [54]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1, 2, 3, 4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 

In [50]:
birboyut

array([1, 2, 3, 4])

In [55]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutucuları**

In [47]:
np.zeros(7)#7 sıfırdan tek oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.zeros((2,3),dtype=int) #* sıfırdan oluşan 2 boyutlu oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
np.ones(3)

array([1., 1., 1.])

In [58]:
np.full((4,3),5)#5 sayısından oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [59]:
np.arange(2,22,5) #başlangıç, bitiş ve artış değerine göre oluşturma

array([ 2,  7, 12, 17])

In [60]:
np.linspace(2,10,num=7) #başlangıç ve bitiş değeri aralığında belirtilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [61]:
np.random.randint(0,10,5)#0-10 arasında rastgele 5 sayıdan oluşan bir boyut dizi 

array([5, 2, 4, 5, 6])

In [62]:
np.random.randint(0,10,(5,2))#0-10 aralığında  5*2 rastgele sayıdan oluşan 2 boyutlu bir dizi 

array([[2, 1],
       [9, 1],
       [0, 5],
       [9, 9],
       [4, 4]])

**dizi ile işlemler**

In [64]:
#dizilerin eleman sayısını öğrenmek için shape komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [65]:
#ndim dizi boyutu öğrenmek için kullanılır
dizi.ndim

2

In [66]:
#size dizisindeki toplam eleman sayısını gösterir
dizi.size

12

In [67]:
dizi.itemsize #dizideki her bir elemanın bayt cinsindeki verir

4